-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "createddate" DROP DEFAULT,
ALTER COLUMN "createddate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updateddate" DROP DEFAULT,
ALTER COLUMN "updateddate" SET DATA TYPE TIMESTAMP(3);
